### PR TITLE
Replacing read.table and write.table for vertex functions with readr equivalent

### PR DESCRIPTION
**Pull request by vfonov**
I made a few changes:
- switched to readr for vertex files input/output
- switched from lsof to analyzing /proc/pid/fd
- added ability to specify column for vertex stats
- rerun roxygen to regenrate documentation
- added tests to test that new reader works as expected

### CODE REVIEW

**Comment by cfhammill** [comment]
This looks great. Thanks Vlad. Being able to read zipped vertex files is a big plus. Also thanks for fixing the configuration!

**Comment by vfonov** [comment]
Hm, I also noticed that anatAnova anatLM tests fail ...

**Comment by cfhammill** [comment]
That I think is likely a change from our end. I'll investigate next week

**Comment by cfhammill** [comment]
Hey @vfonov, our CI builds are failing with a cmake error. Any chance you can take a quick look:

https://travis-ci.org/Mouse-Imaging-Centre/RMINC/jobs/501684569#L6316

**Pull request merged**
