### PR TITLE
Added attributes to the vertexMean and friends to make it compatible with vertexLm

### PR DESCRIPTION
**Pull request by vfonov**
Added attributes to thevertexMean,vertexVar etc to make it compatible with vertexLm, added tests for writeVertex

### CODE REVIEW

**Comment by vfonov** [comment]
@cfhammill  - potentially more changes are coming....

**Comment by cfhammill** [comment]
I'm not sure I understand what problem this fixes. Are there functions downstream of `mincMean` (for example) that expect these attributes?

**Comment by vfonov** [comment]
https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/R/minc_interface.R#L982 - uses colnames which doesn't work with vertexMean , without my changes.

**Comment by gdevenyi** [comment]
I can merge this in, it has all of Yohann's fixes plus the Vlad additions.

@vfonov can you confirm develop-tidy functional?

**Comment by gdevenyi** [comment]
I can confirm his fixes work, I've used them.

**Pull request merged**
