### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by cfhammill**
I've fixed the bug causing testbed failure at MICe,
added functionality for converting civet results to dplyr compliant data.frames
improved some documentation

### CODE REVIEW

**Comment by mcvaneede** [comment]
I was a bit too quick on this one... Should actually have pulled this into the develop branch. Next time! Thanks Chris!

**Comment by bcdarwin** [comment]
Doesn't hard-coding paths to /axiom2 break this for non-MICers?

Nitpick: R can get a tmpdir programatically, which is useful in case the user wants to change it (say via an environment variable).

**Comment by gdevenyi** [comment]
Yes please, against hard coded paths :)

**Comment by cfhammill** [comment]
Thanks Ben, I've made changes to remove hard-coded paths in the RMINC.Rproj file, and it now programatically generates a temporary directory (nice tip). Issuing the pull request now.

**Comment by bcdarwin** [comment]
Going to move this to develop.

**Pull request merged**
